basePath: /api
host: 127.0.0.1:9543
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/support
  description: This is a sample e-commerce API for managing users, products, and orders.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms/
  title: E-commerce API
  version: "1.0"
paths: {}
swagger: "2.0"
